### ISSUE TITLE
Assign TEMPLATE_DIR on load rather than at installation

### ISSUE THREAD

**Issue by mtmorgan** [jokergoo/cola#13]
This

https://github.com/jokergoo/cola/blob/6d91eaf1f0df5bd7381f764bd4a068a8932d00a2/R/report.R#L69

assigns TEMPLATE_DIR to the path when the package is being installed, rather than when it is loaded or attached. This will cause problems in a future R where '[staged install][1]' is implemented. A better practice is along the lines of
```
TEMPLATE_DIR <- NULL

.onLoad <- function(...) {
    TEMPLATE_DIR <- system.file(package="cola", ...
}
```
[1]: https://developer.r-project.org/Blog/public/2019/02/14/staged-install/index.html

**Comment by jokergoo** [comment]
Thanks! I set it when I test the package and I forgot to change it back.
