### ISSUE TITLE
一个输入数据的问题

### ISSUE THREAD

**Issue by ShixiangWang** [jokergoo/cola#145]
顾博你好，

我最近一个聚类任务的需求，之前考虑使用 consensusclusterplus 这个包，最近看你的 cola 包很不错，所以想试一试。这里有一个关于输入数据的问题，可能跟包本身无关，但你在这方面的探索经验丰富，所以想咨询一下。

我计划输入进行聚类的数据矩阵行是突变类型的计数而列是样本，目前我想同时纳入不同突变类型的实际计数值和它在样本中的突变类型贡献比例。

例如，样本 S1 的 A>T 突变数是100，它占所有突变数的比例是 10%，我想同时使用者两者信息，但由于一种值在[0, 1]范围，另一种可能在[0, 10000]范围，不知道这样去聚类是否合理，然后是否有必要统一对每一行数据标准化。

我一开始也考虑过只使用单一的特征，即只考虑突变占比或者突变数量，但我感觉这种都无法纳入所有的变异 Variance 信息。

- 如果只考虑占比，那么可能有 100 个突变和 1000 个突变的样本占比值是一样的
- 如果只考虑突变数，那么样本内突变类型占比的构成信息就被减弱了

望指点一下。

祝好，

王诗翔

**Comment by jokergoo** [comment]
所以你既想使用绝对的数值量，又想保留相对的数值量。要知道绝对和相对是互相矛盾的。：）

我建议你可以做两次consensus clustering，一次使用绝对的突变数，一次使用相对的比例，最后比较这两个分类，例如相似的地方和不一样的地方。这两个聚类其实是对数据进行两个不同角度的观察，相同的聚类和不同的聚类结果可能都是有意义的。

在对相对的比例值进行聚类时，我建议先做一些预处理，将突变数特别小的去掉（如果它们不重要的话）。

**Comment by ShixiangWang** [comment]
好的，我明天试一试，你说 两个角度 这个很对。我目前有整合两个角度的想法是：不改相对值，而绝对值想要对每一个突变类型根据所有的样本做一个z score之类的标准化，这样它们的取值范围差异就不大了，不知道这样做是否合适？

**Comment by ShixiangWang** [comment]
@jokergoo 我试了下绝对值，但有点方法运行会报错，我不清楚这个是代码的问题还是数据的问题，如果是数据的问题，是否应该设置一个内部操作跳过报错的方法组合？

```
> rl_abs <- run_all_consensus_partition_methods(mat_abs[, select_samps], mc.cores = 8)
* on a 10x500 matrix.
* calculate top-values.
  - calculate SD score for 10 rows.
  - calculate CV score for 10 rows.
  - calculate MAD score for 10 rows.
  - calculate ATC score for 10 rows.
------------------------------------------------------------
* running partition by SD:skmeans. 1/20
* run SD:skmeans on a 10x500 matrix.
* SD values have already been calculated. Get from cache.
* rows are scaled before sent to partition, method: 'z-score' (x - mean)/sd
* get top 1 rows by SD method
  - skmeans repeated for 50 times by row-sampling (p = 0.8) from top 1 rows (8 cores).
* get top 2 rows by SD method
  - skmeans repeated for 50 times by row-sampling (p = 0.8) from top 2 rows (8 cores).
* get top 3 rows by SD method
  - skmeans repeated for 50 times by row-sampling (p = 0.8) from top 3 rows (8 cores).
* wrap results for k = 2
* wrap results for k = 3
* wrap results for k = 4
* wrap results for k = 5
* wrap results for k = 6
* adjust class labels between different k.
* SD:skmeans used 40.935 secs.
------------------------------------------------------------
* running partition by CV:skmeans. 2/20
* run CV:skmeans on a 10x500 matrix.
* CV values have already been calculated. Get from cache.
* rows are scaled before sent to partition, method: 'z-score' (x - mean)/sd
* get top 1 rows by CV method
  - skmeans repeated for 50 times by row-sampling (p = 0.8) from top 1 rows (8 cores).
* get top 2 rows by CV method
  - skmeans repeated for 50 times by row-sampling (p = 0.8) from top 2 rows (8 cores).
* get top 3 rows by CV method
  - skmeans repeated for 50 times by row-sampling (p = 0.8) from top 3 rows (8 cores).
* wrap results for k = 2
* wrap results for k = 3
* wrap results for k = 4
* wrap results for k = 5
* wrap results for k = 6
* adjust class labels between different k.
* CV:skmeans used 40.997 secs.
------------------------------------------------------------
* running partition by MAD:skmeans. 3/20
* run MAD:skmeans on a 10x500 matrix.
* MAD values have already been calculated. Get from cache.
* rows are scaled before sent to partition, method: 'z-score' (x - mean)/sd
* get top 1 rows by MAD method
  - skmeans repeated for 50 times by row-sampling (p = 0.8) from top 1 rows (8 cores).
You have an error when doing partition for MAD:skmeans. 
Following is the call stack:
[[1]]
run_all_consensus_partition_methods(mat_abs[, select_samps], 
    mc.cores = 8)

[[2]]
lapply(seq_len(nrow(comb)), function(i) {
    tm = comb[i, 1]
    pm = comb[i, 2]
    if (verbose) 
        qqcat("------------------------------------------------------------\n")
    if (verbose) 
        qqcat("* running partition by @{tm}:@{pm}. @{i}/@{nrow(comb)}\n")
    try_and_trace(res <- consensus_partition(top_value_method = tm, 
        partition_method = pm, max_k = max_k, anno = anno, anno_col = anno_col, 
        .env = .env, verbose = verbose, top_n = top_n, sample_by = sample_by, 
        p_sampling = p_sampling, partition_repeat = partition_repeat, 
        scale_rows = scale_rows, mc.cores = mc.cores), qq("You have an error when doing partition for @{tm}:@{pm}."))
    return(res)
})

[[3]]
FUN(X[[i]], ...)

[[4]]
try_and_trace(res <- consensus_partition(top_value_method = tm, 
    partition_method = pm, max_k = max_k, anno = anno, anno_col = anno_col, 
    .env = .env, verbose = verbose, top_n = top_n, sample_by = sample_by, 
    p_sampling = p_sampling, partition_repeat = partition_repeat, 
    scale_rows = scale_rows, mc.cores = mc.cores), qq("You have an error when doing partition for @{tm}:@{pm}."))

[[5]]
withCallingHandlers(expr, error = function(e) {
    cat(message, "\n")
    cat("Following is the call stack:\n")
    print(sys.calls())
})

[[6]]
consensus_partition(top_value_method = tm, partition_method = pm, 
    max_k = max_k, anno = anno, anno_col = anno_col, .env = .env, 
    verbose = verbose, top_n = top_n, sample_by = sample_by, 
    p_sampling = p_sampling, partition_repeat = partition_repeat, 
    scale_rows = scale_rows, mc.cores = mc.cores)

[[7]]
system.time(res <- .consensus_partition(data = data, top_value_method = top_value_method, 
    top_n = top_n, partition_method = partition_method, k = 2:max_k, 
    p_sampling = p_sampling, sample_by = sample_by, partition_repeat = partition_repeat, 
    partition_param = partition_param, anno = anno, anno_col = anno_col, 
    scale_rows = scale_rows, verbose = verbose, mc.cores = mc.cores, 
    prefix = prefix, .env = .env))

[[8]]
.consensus_partition(data = data, top_value_method = top_value_method, 
    top_n = top_n, partition_method = partition_method, k = 2:max_k, 
    p_sampling = p_sampling, sample_by = sample_by, partition_repeat = partition_repeat, 
    partition_param = partition_param, anno = anno, anno_col = anno_col, 
    scale_rows = scale_rows, verbose = verbose, mc.cores = mc.cores, 
    prefix = prefix, .env = .env)

[[9]]
rbind(param, lt[[i]]$param)

[[10]]
rbind(deparse.level, ...)

[[11]]
.handleSimpleError(function (e) 
{
    cat(message, "\n")
    cat("Following is the call stack:\n")
    print(sys.calls())
}, "$ operator is invalid for atomic vectors", base::quote(NULL))

[[12]]
h(simpleError(msg, call))

Error: $ operator is invalid for atomic vectors
In addition: Warning message:
In mclapply(seq_len(partition_repeat), function(j) { :
  scheduled core 5 encountered error in user code, all values of the job will be affected
Timing stopped at: 33.28 2.887 6.236
```

**Comment by jokergoo** [comment]
可能是你只有10行的原因，一般来说cola作用在一个完整的矩阵上，而不是经过pre-selection后的一个小的矩阵，这也是为什么需要top value method的原因，如果你只有10行，我觉的可能根本用不上consensus clustering。

你试试将top_n设为10看看会不会有错误。

**Comment by jokergoo** [comment]
你可以将你用的这个矩阵发给我么`mat_abs[, select_samps]`，我看看究竟是什么原因造成这个错误。

**Comment by ShixiangWang** [comment]
@jokergoo 你说的对，我的特征是比较少，我之前没有注意到这个函数会开始筛选一些特征。我先试试 top_n 这个参数，我不需要挑选特征，但想要利用目前已有的特征对样本完成一致性聚类。数据附上了～

[test_mat.RData.zip](https://github.com/jokergoo/cola/files/5728856/test_mat.RData.zip)

**Comment by ShixiangWang** [comment]
@jokergoo 我用 top_n 没有问题，非常感谢。有一个结果解读的疑问，我看到多个图出现 p1...pn 这些变量，例如下面图左下方，看指示是一种概率？我不知道该怎么理解它以及它是如何计算的（和输入矩阵的关系）。我看到 vignette 有 Find signatures 一节，p 变量指的就是有分类作用的 signatures？

![image](https://user-images.githubusercontent.com/25057508/102971871-20c07880-4535-11eb-9c61-7a728eaf3721.png)

**Comment by ShixiangWang** [comment]
顾博，我在看预测文档是有一个疑问，希望指教，这也是我之前自己做建模和预测时有的一个疑问，

![image](https://user-images.githubusercontent.com/25057508/102973029-07203080-4537-11eb-9c17-fd124de6e4f3.png)

需要预测的矩阵需要按行进行同样的标准化操作，但假设需要进行预测的数据很少，例如只有一个样本，那么就是一个 `n x 1` 的矩阵，这个是没法对行做标准化的；我能想到的办法是将新的数据加入原矩阵一起预测，有没有不需要原矩阵的策略呢？

**Comment by hzongyao** [comment]
请问如果我的数据是 seurat 对象里的矩阵，应该传入哪个矩阵合适呢？count？ data ？ scale data ？ 谢谢！

**Comment by ShixiangWang** [comment]
@hzongyao 默认会进行标准化，所以传入原始矩阵就可以，记得需要行列名

**Comment by hzongyao** [comment]
@ShixiangWang 谢谢回复，我还在考虑一个问题，对于单细胞数据，这种方法怎么解决潜在的批次效应问题呢？还有就是我很好奇这种分类的结果会不会和常规的 seurat+harmony 流程得到的聚类结果相似？谢谢！

**Comment by ShixiangWang** [comment]
不知道，也许先批次矫正后再聚类？

**Comment by hzongyao** [comment]
@ShixiangWang 确实使用 harmony 之后会得到一个新的 harmony 矩阵，seurat 标准流程中也是基于这个矩阵重新降维聚类分群，但是使用 harmony 矩阵作为 该方法的输入，理论上可以得到一个结果，但是对于结果的解释（比如后续探讨 signature ）可能就会存在问题

**Comment by ShixiangWang** [comment]
@jokergoo 有一个关于 signature 热图的疑问🤔️

下面这个热图默认没有添加行名的参数，我看到有支持行注释所以按照这种方式添加，但发现顺序是有变化，这正常吗？

![image](https://user-images.githubusercontent.com/25057508/103126918-cd802e80-46ca-11eb-93f9-89824abcf9ea.png)

注释代码：

```r
left_annotation = rowAnnotation(foo = anno_text(paste0("Sig", c(1:4, 6:11))))
```

我感觉它应该是根据输入矩阵的顺序变化过，但结果数据显示是和原矩阵顺序一一对应的

![image](https://user-images.githubusercontent.com/25057508/103127028-3667a680-46cb-11eb-98bd-28156a5ea2f0.png)

你在文档中的说明：`which_row: row indices corresponding to the input matrix.`，这就比较奇怪了，输入对应的顺序没有变，我输入矩阵顺序也没有变，行注释顺序也没有变，图中的标签怎么变了

```
# 输入矩阵行名
rownames(mat_abs)
 [1] "Abs_Sig1"  "Abs_Sig2"  "Abs_Sig3"  "Abs_Sig4"  "Abs_Sig6"  "Abs_Sig7"  "Abs_Sig8"  "Abs_Sig9"  "Abs_Sig10" "Abs_Sig11"
```

---

![image](https://user-images.githubusercontent.com/25057508/103127099-79c21500-46cb-11eb-98ac-3d9695b89d5d.png)

**Comment by jokergoo** [comment]
> @jokergoo 我用 top_n 没有问题，非常感谢。有一个结果解读的疑问，我看到多个图出现 p1...pn 这些变量，例如下面图左下方，看指示是一种概率？我不知道该怎么理解它以及它是如何计算的（和输入矩阵的关系）。我看到 vignette 有 Find signatures 一节，p 变量指的就是有分类作用的 signatures？
> 
> ![image](https://user-images.githubusercontent.com/25057508/102971871-20c07880-4535-11eb-9c61-7a728eaf3721.png)

`p1`, ... `pn`是每个样本属于各个类的概率

**Comment by jokergoo** [comment]
> 顾博，我在看预测文档是有一个疑问，希望指教，这也是我之前自己做建模和预测时有的一个疑问，
> 
> ![image](https://user-images.githubusercontent.com/25057508/102973029-07203080-4537-11eb-9c17-fd124de6e4f3.png)
> 
> 需要预测的矩阵需要按行进行同样的标准化操作，但假设需要进行预测的数据很少，例如只有一个样本，那么就是一个 `n x 1` 的矩阵，这个是没法对行做标准化的；我能想到的办法是将新的数据加入原矩阵一起预测，有没有不需要原矩阵的策略呢？

因为需要两个矩阵在一个scale下，你可以使用第一个矩阵的row mean和row sd对你第二个`nx1`的矩阵做归一化。

**Comment by jokergoo** [comment]
> 请问如果我的数据是 seurat 对象里的矩阵，应该传入哪个矩阵合适呢？count？ data ？ scale data ？ 谢谢！

选择哪一个矩阵是用户的问题。cola缺省下自动对行做scalling

**Comment by jokergoo** [comment]
> @ShixiangWang 谢谢回复，我还在考虑一个问题，对于单细胞数据，这种方法怎么解决潜在的批次效应问题呢？还有就是我很好奇这种分类的结果会不会和常规的 seurat+harmony 流程得到的聚类结果相似？谢谢！

cola只做聚类，不考虑其他的因素。如果有潜在的批次效应，cola可能会找到

**Comment by jokergoo** [comment]
> @jokergoo 有一个关于 signature 热图的疑问🤔️
> 
> 下面这个热图默认没有添加行名的参数，我看到有支持行注释所以按照这种方式添加，但发现顺序是有变化，这正常吗？
> 
> ![image](https://user-images.githubusercontent.com/25057508/103126918-cd802e80-46ca-11eb-93f9-89824abcf9ea.png)
> 
> 注释代码：
> 
> ```r
> left_annotation = rowAnnotation(foo = anno_text(paste0("Sig", c(1:4, 6:11))))
> ```
> 
> 我感觉它应该是根据输入矩阵的顺序变化过，但结果数据显示是和原矩阵顺序一一对应的
> 
> ![image](https://user-images.githubusercontent.com/25057508/103127028-3667a680-46cb-11eb-98bd-28156a5ea2f0.png)
> 
> 你在文档中的说明：`which_row: row indices corresponding to the input matrix.`，这就比较奇怪了，输入对应的顺序没有变，我输入矩阵顺序也没有变，行注释顺序也没有变，图中的标签怎么变了
> 
> ```
> # 输入矩阵行名
> rownames(mat_abs)
>  [1] "Abs_Sig1"  "Abs_Sig2"  "Abs_Sig3"  "Abs_Sig4"  "Abs_Sig6"  "Abs_Sig7"  "Abs_Sig8"  "Abs_Sig9"  "Abs_Sig10" "Abs_Sig11"
> ```
> 
> ![image](https://user-images.githubusercontent.com/25057508/103127099-79c21500-46cb-11eb-98ac-3d9695b89d5d.png)

谢谢你这条回复，我从来没有测试过left_annotation和right_annotation，我看看代码

**Comment by ShixiangWang** [comment]
> #146

好的，非常感谢。这几天使用过程中，我个人目前的感觉是返回的数据框的顺序跟图中行的顺序是没有关系的，你的代码应该没有问题，不过还需要你确定下。

**Comment by jokergoo** [comment]
> > #146
> 
> 好的，非常感谢。这几天使用过程中，我个人目前的感觉是返回的数据框的顺序跟图中行的顺序是没有关系的，你的代码应该没有问题，不过还需要你确定下。

是的，返回的数据框应该是自然排序的，图中的行是经过聚类的。

另一个问题是你的矩阵只有10行，我不确定cola是不是合适应用在这上面。

**Comment by ShixiangWang** [comment]
@jokergoo 谢谢。我的使用结果显示是没有什么问题的，不同的 top select method 差不多，而不同的聚类方法影响比较大。因为你的框架是通用的，从流程图也看得出来。

再次感谢哈～
