### ISSUE TITLE
export report figures as SVG or PDF

### ISSUE THREAD

**Issue by Daria150393** [jokergoo/cola#151]
Great package!

It would be really helpful to be able to export figures in PDF- or SVG format!
Is this possible? This would be amazing!

**Comment by jokergoo** [comment]
The code in the report is all runnable. You can just copy and paste the code and manually save figures in PDF or SVG.

**Comment by Daria150393** [comment]
When I try to compile the code from report.R and change "\\.png$" in line 277 to "\\.svg$", I get the following error message:
Error: `cola_report()` cannot be run under test mode.

Do I need to download all scripts? I seems not to be possible to just change report.R.

**Comment by jokergoo** [comment]
No, I didn't mean to directly modify the source code of `report.R`. What I mean is you can copy the code as in https://jokergoo.github.io/cola_examples/Golub_leukemia/Golub_leukemia_subgroup_cola_report/cola_report.html, just like how you run code in vignettes when you learn a new package.

**Comment by Daria150393** [comment]
Sorry for the misunderstanding. Works perfectly! Thank you
