### ISSUE TITLE
少量基因数目做聚类问题

### ISSUE THREAD

**Issue by LiangZhao21** [jokergoo/cola#152]
作者你好，我想只取少量基因（比如20个）针对这些基因做聚类，同时我不想舍弃任何一个基因，这种情况下`all_top_value_methods`参数其实我不需要用到，我试过使用所有top_value_methods，并且`top_n`我设置的是20（所有基因数），但是最后每种聚类方法下的不同top_value_methods得到的结果略有不同。我只需要`partition_method`参数，请问`run_all_consensus_partition_methods`代码需要怎么修改呢？
谢谢

**Comment by jokergoo** [comment]
你可以

```r
run_all_consensus_partition_methods(mat, top_n = nrow(mat), top_value_method = "SD")
```

**Comment by LiangZhao21** [comment]
这样是不是相当于指定按照SD取基因，基因数是全部数目，但是如果我选择CV、MAD等其他的方法最后结果是有同的，我没太明白您说的选SD是什么意思。

**Comment by jokergoo** [comment]
因为其中会在20个基因中随机选取80%，然后重复进行聚类，最后得到consensus clustering的结果。

**Comment by LiangZhao21** [comment]
一定需要随机选取吗，我想要直接包含所有基因，每个基因都认为有用不可删除的，这个函数可以实现吗？如果不可以，选SD最好还是其他CV、ATC这些都可以用？谢谢

**Comment by jokergoo** [comment]
那就不是consensus clustering，你用普通的聚类就可以了。
