### ISSUE TITLE
minimum number of k clusters

### ISSUE THREAD

**Issue by LucaGiudice** [jokergoo/cola#158]
Hi,
is there a way to let the method avoid to perform clustering for a number k lower than a threshold? 
For example, in the function: run_all_consensus_partition_methods, it is possible to set "max_k" but there is not "min_k".
I think that it would be very useful to skip ks that are not interesting for the user.
For example, I usually work with a high number of clusters and the method performs clustering with all the k lower than mine max_k  that is set to 15 or higher. As result, I have to wait 20 minutes even with 16 cores and I end up with a huge report that contains a lot of unneeded details.

Thank you already for your future answer.

**Comment by jokergoo** [comment]
Since other people also have similar request, I will support it soon!

**Comment by jokergoo** [comment]
By the way, since you are expecting a large number of groups, normal consensus clustering might not work well. In the current GitHub version of cola, there is a new function `hierarchical_partition()` which applies consensus clustering in a hierarchical way. It can detect many subgroups. Maybe you can have a try :)

**Comment by jokergoo** [comment]
Now I added a new argument `k` in the function. You can set `k` as a vector of k that you want to try.

```r
run_all_consensus_partition_methods(..., k = 10:15)
```

**Comment by LucaGiudice** [comment]
Thank you very much for quickly solving the issue.
About datasets including many clusters, I never needed the hierarchical_partition() function because the main approach with run_all_consensus_partition_methods() works nice.  Of course, it may depends by the context application. I used your method in three projects to test if patient's genetic profiles described the treatment or disease properly. In this context, I don't want to discover new groups because the patient outcome/status is clear, so I don't apply run_all_consensus_partition_methods() with 20k sequenced genes/miRNAs/lncRNAs. I perform a light feature selection for guiding the clustering without overfitting the partition techniques (e.g. 5k best genes instead of 20k) and I use cola as semi-supervised clustering.  So far, it allowed me to find out properly if some patients were behaving as not supposed to (i.e. outliers) or the contrary.

**Comment by jokergoo** [comment]
Good! happy it is useful for you :)
