### ISSUE TITLE
bug report: cat(n_cores) : object 'n_cores' not found when running cola_report()

### ISSUE THREAD

**Issue by htc502** [jokergoo/cola#165]
Hi guys, 
really nice and comprehensive tool for clustering analysis! When I run cola_report() I got an error:
cola_report(res1,output_dir = 'cola_report')
* generating cola report for `res1` (a ConsensusPartitionList object)
* the report is available at xxxxxxxxxxx/cola_report/cola_report.html
* generating R markdown file based on template report
Error in cat(n_cores) : object 'n_cores' not found
* rendering R markdown file to html by knitr
* making density heatmap of global distribution for each sample (366 samples)* report is at xxxxxxxx/cola_report/cola_report.html
* In total, the report generation uses 0.117 secs.
* 
I guess for some reason your "n_cores" variable is not visable to the downstream code chunks in the template reporting file?

Thanks,

**Comment by jokergoo** [comment]
Can you update the package from GitHub? I think that was a bug and has been fixed.
