### ISSUE TITLE
Error when doing partition for ATC:NMF 

### ISSUE THREAD

**Issue by venkan** [jokergoo/cola#167]
Hi,

I'm using `run_all_consensus_partition_methods` function with ATC and having an error. I have a matrix with around 53k genes as rows and 63 samples as columns. 

But there are no errors with SD, MAD, CV. I see the error only with ATC.

```
rl = run_all_consensus_partition_methods(m, 
     mc.cores = 4, top_n = c(1000,2000,3000),
     anno = data.frame(subtype = patho_subtype3),
     anno_col = list(subtype = subtype_col))
```
* on a 53760x63 matrix.
* calculate top-values.
  - calculate SD score for 53760 rows.
  - calculate CV score for 53760 rows.
  - calculate MAD score for 53760 rows.
  - calculate ATC score for 53760 rows.
------------------------------------------------------------
* running partition by SD:NMF. 1/24
* on a 53760x63 matrix.
* SD values have already been calculated. Get from cache.
* rows are scaled before sent to partition, method: 'min-max' (x - min)/(max - min)
* get top 1000 rows by SD method
  - NMF repeated for 50 times by row-sampling (p = 0.8) from top 1000 rows (4 cores).
* get top 2000 rows by SD method
  - NMF repeated for 50 times by row-sampling (p = 0.8) from top 2000 rows (4 cores).
* get top 3000 rows by SD method
  - NMF repeated for 50 times by row-sampling (p = 0.8) from top 3000 rows (4 cores).
* wrap results for k = 2
* wrap results for k = 3
* wrap results for k = 4
* wrap results for k = 5
* wrap results for k = 6
* adjust class labels between different k.
* SD:NMF used 38.08443 mins.
------------------------------------------------------------
* running partition by CV:NMF. 2/24
* on a 53760x63 matrix.
* CV values have already been calculated. Get from cache.
* rows are scaled before sent to partition, method: 'min-max' (x - min)/(max - min)
* get top 1000 rows by CV method
  - NMF repeated for 50 times by row-sampling (p = 0.8) from top 1000 rows (4 cores).
* get top 2000 rows by CV method
  - NMF repeated for 50 times by row-sampling (p = 0.8) from top 2000 rows (4 cores).
* get top 3000 rows by CV method
  - NMF repeated for 50 times by row-sampling (p = 0.8) from top 3000 rows (4 cores).
* wrap results for k = 2
* wrap results for k = 3
* wrap results for k = 4
* wrap results for k = 5
* wrap results for k = 6
* adjust class labels between different k.
* CV:NMF used 1.716457 hours.
------------------------------------------------------------
* running partition by MAD:NMF. 3/24
* on a 53760x63 matrix.
* MAD values have already been calculated. Get from cache.
* rows are scaled before sent to partition, method: 'min-max' (x - min)/(max - min)
* get top 1000 rows by MAD method
  - NMF repeated for 50 times by row-sampling (p = 0.8) from top 1000 rows (4 cores).
* get top 2000 rows by MAD method
  - NMF repeated for 50 times by row-sampling (p = 0.8) from top 2000 rows (4 cores).
* get top 3000 rows by MAD method
  - NMF repeated for 50 times by row-sampling (p = 0.8) from top 3000 rows (4 cores).
* wrap results for k = 2
* wrap results for k = 3
* wrap results for k = 4
* wrap results for k = 5
* wrap results for k = 6
* adjust class labels between different k.
* MAD:NMF used 40.93897 mins.
------------------------------------------------------------
* running partition by ATC:NMF. 4/24
* on a 53760x63 matrix.
* ATC values have already been calculated. Get from cache.
* rows are scaled before sent to partition, method: 'min-max' (x - min)/(max - min)
* get top 1000 rows by ATC method
  - NMF repeated for 50 times by row-sampling (p = 0.8) from top 1000 rows (4 cores).
You have an error when doing partition for ATC:NMF. 
Following is the call stack:
[[1]]
run_all_consensus_partition_methods(m, mc.cores = 4, top_n = c(1000, 
    2000, 3000), anno = data.frame(subtype = patho_subtype3), 
    anno_col = list(subtype = subtype_col))

[[2]]
lapply(seq_len(nrow(comb)), function(i) {
    tm = comb[i, 1]
    pm = comb[i, 2]
    if (verbose) 
        qqcat("------------------------------------------------------------\n")
    if (verbose) 
        qqcat("* running partition by @{tm}:@{pm}. @{i}/@{nrow(comb)}\n")
    try_and_trace(res <- consensus_partition(top_value_method = tm, 
        partition_method = pm, max_k = max_k, anno = anno, anno_col = anno_col, 
        .env = .env, verbose = verbose, top_n = top_n, sample_by = sample_by, 
        p_sampling = p_sampling, partition_repeat = partition_repeat, 
        scale_rows = scale_rows, mc.cores = mc.cores), qq("You have an error when doing partition for @{tm}:@{pm}."))
    return(res)
})

[[3]]
FUN(X[[i]], ...)

[[4]]
try_and_trace(res <- consensus_partition(top_value_method = tm, 
    partition_method = pm, max_k = max_k, anno = anno, anno_col = anno_col, 
    .env = .env, verbose = verbose, top_n = top_n, sample_by = sample_by, 
    p_sampling = p_sampling, partition_repeat = partition_repeat, 
    scale_rows = scale_rows, mc.cores = mc.cores), qq("You have an error when doing partition for @{tm}:@{pm}."))

[[5]]
withCallingHandlers(expr, error = function(e) {
    cat(message, "\n")
    cat("Following is the call stack:\n")
    print(sys.calls())
})

[[6]]
consensus_partition(top_value_method = tm, partition_method = pm, 
    max_k = max_k, anno = anno, anno_col = anno_col, .env = .env, 
    verbose = verbose, top_n = top_n, sample_by = sample_by, 
    p_sampling = p_sampling, partition_repeat = partition_repeat, 
    scale_rows = scale_rows, mc.cores = mc.cores)

[[7]]
system.time(res <- .consensus_partition(data = data, top_value_method = top_value_method, 
    top_n = top_n, partition_method = partition_method, k = 2:max_k, 
    p_sampling = p_sampling, sample_by = sample_by, partition_repeat = partition_repeat, 
    partition_param = partition_param, anno = anno, anno_col = anno_col, 
    scale_rows = scale_rows, verbose = verbose, mc.cores = mc.cores, 
    .env = .env))

[[8]]
.consensus_partition(data = data, top_value_method = top_value_method, 
    top_n = top_n, partition_method = partition_method, k = 2:max_k, 
    p_sampling = p_sampling, sample_by = sample_by, partition_repeat = partition_repeat, 
    partition_param = partition_param, anno = anno, anno_col = anno_col, 
    scale_rows = scale_rows, verbose = verbose, mc.cores = mc.cores, 
    .env = .env)

[[9]]
rbind(param, lt[[i]]$param)

[[10]]
rbind(deparse.level, ...)

[[11]]
.handleSimpleError(function (e) 
{
    cat(message, "\n")
    cat("Following is the call stack:\n")
    print(sys.calls())
}, "$ operator is invalid for atomic vectors", base::quote(NULL))

[[12]]
h(simpleError(msg, call))

Error: $ operator is invalid for atomic vectors
In addition: Warning message:
In mclapply(seq_len(partition_repeat), function(j) { :
  all scheduled cores encountered errors in user code
Timing stopped at: 3.332 3.451 4.742

**Comment by venkan** [comment]
> Hi,
> 
> I'm using `run_all_consensus_partition_methods` function with ATC and having an error. I have a matrix with around 53k genes as rows and 63 samples as columns.
> 
> But there are no errors with SD, MAD, CV. I see the error only with ATC.
> 
> ```
> rl = run_all_consensus_partition_methods(m, 
>      mc.cores = 4, top_n = c(1000,2000,3000),
>      anno = data.frame(subtype = patho_subtype3),
>      anno_col = list(subtype = subtype_col))
> ```
> 
> * on a 53760x63 matrix.
> * calculate top-values.
>   
>   * calculate SD score for 53760 rows.
>   * calculate CV score for 53760 rows.
>   * calculate MAD score for 53760 rows.
>   * calculate ATC score for 53760 rows.
> 
> * running partition by SD:NMF. 1/24
> * on a 53760x63 matrix.
> * SD values have already been calculated. Get from cache.
> * rows are scaled before sent to partition, method: 'min-max' (x - min)/(max - min)
> * get top 1000 rows by SD method
>   
>   * NMF repeated for 50 times by row-sampling (p = 0.8) from top 1000 rows (4 cores).
> * get top 2000 rows by SD method
>   
>   * NMF repeated for 50 times by row-sampling (p = 0.8) from top 2000 rows (4 cores).
> * get top 3000 rows by SD method
>   
>   * NMF repeated for 50 times by row-sampling (p = 0.8) from top 3000 rows (4 cores).
> * wrap results for k = 2
> * wrap results for k = 3
> * wrap results for k = 4
> * wrap results for k = 5
> * wrap results for k = 6
> * adjust class labels between different k.
> * SD:NMF used 38.08443 mins.
> 
> * running partition by CV:NMF. 2/24
> * on a 53760x63 matrix.
> * CV values have already been calculated. Get from cache.
> * rows are scaled before sent to partition, method: 'min-max' (x - min)/(max - min)
> * get top 1000 rows by CV method
>   
>   * NMF repeated for 50 times by row-sampling (p = 0.8) from top 1000 rows (4 cores).
> * get top 2000 rows by CV method
>   
>   * NMF repeated for 50 times by row-sampling (p = 0.8) from top 2000 rows (4 cores).
> * get top 3000 rows by CV method
>   
>   * NMF repeated for 50 times by row-sampling (p = 0.8) from top 3000 rows (4 cores).
> * wrap results for k = 2
> * wrap results for k = 3
> * wrap results for k = 4
> * wrap results for k = 5
> * wrap results for k = 6
> * adjust class labels between different k.
> * CV:NMF used 1.716457 hours.
> 
> * running partition by MAD:NMF. 3/24
> * on a 53760x63 matrix.
> * MAD values have already been calculated. Get from cache.
> * rows are scaled before sent to partition, method: 'min-max' (x - min)/(max - min)
> * get top 1000 rows by MAD method
>   
>   * NMF repeated for 50 times by row-sampling (p = 0.8) from top 1000 rows (4 cores).
> * get top 2000 rows by MAD method
>   
>   * NMF repeated for 50 times by row-sampling (p = 0.8) from top 2000 rows (4 cores).
> * get top 3000 rows by MAD method
>   
>   * NMF repeated for 50 times by row-sampling (p = 0.8) from top 3000 rows (4 cores).
> * wrap results for k = 2
> * wrap results for k = 3
> * wrap results for k = 4
> * wrap results for k = 5
> * wrap results for k = 6
> * adjust class labels between different k.
> * MAD:NMF used 40.93897 mins.
> 
> * running partition by ATC:NMF. 4/24
> * on a 53760x63 matrix.
> * ATC values have already been calculated. Get from cache.
> * rows are scaled before sent to partition, method: 'min-max' (x - min)/(max - min)
> * get top 1000 rows by ATC method
>   
>   * NMF repeated for 50 times by row-sampling (p = 0.8) from top 1000 rows (4 cores).
>     You have an error when doing partition for ATC:NMF.
>     Following is the call stack:
>     [[1]]
>     run_all_consensus_partition_methods(m, mc.cores = 4, top_n = c(1000,
>     2000, 3000), anno = data.frame(subtype = patho_subtype3),
>     anno_col = list(subtype = subtype_col))
> 
> [[2]] lapply(seq_len(nrow(comb)), function(i) { tm = comb[i, 1] pm = comb[i, 2] if (verbose) qqcat("------------------------------------------------------------\n") if (verbose) qqcat("* running partition by @{tm}:@{pm}. @{i}/@{nrow(comb)}\n") try_and_trace(res <- consensus_partition(top_value_method = tm, partition_method = pm, max_k = max_k, anno = anno, anno_col = anno_col, .env = .env, verbose = verbose, top_n = top_n, sample_by = sample_by, p_sampling = p_sampling, partition_repeat = partition_repeat, scale_rows = scale_rows, mc.cores = mc.cores), qq("You have an error when doing partition for @{tm}:@{pm}.")) return(res) })
> 
> [[3]] FUN(X[[i]], ...)
> 
> [[4]] try_and_trace(res <- consensus_partition(top_value_method = tm, partition_method = pm, max_k = max_k, anno = anno, anno_col = anno_col, .env = .env, verbose = verbose, top_n = top_n, sample_by = sample_by, p_sampling = p_sampling, partition_repeat = partition_repeat, scale_rows = scale_rows, mc.cores = mc.cores), qq("You have an error when doing partition for @{tm}:@{pm}."))
> 
> [[5]] withCallingHandlers(expr, error = function(e) { cat(message, "\n") cat("Following is the call stack:\n") print(sys.calls()) })
> 
> [[6]] consensus_partition(top_value_method = tm, partition_method = pm, max_k = max_k, anno = anno, anno_col = anno_col, .env = .env, verbose = verbose, top_n = top_n, sample_by = sample_by, p_sampling = p_sampling, partition_repeat = partition_repeat, scale_rows = scale_rows, mc.cores = mc.cores)
> 
> [[7]] system.time(res <- .consensus_partition(data = data, top_value_method = top_value_method, top_n = top_n, partition_method = partition_method, k = 2:max_k, p_sampling = p_sampling, sample_by = sample_by, partition_repeat = partition_repeat, partition_param = partition_param, anno = anno, anno_col = anno_col, scale_rows = scale_rows, verbose = verbose, mc.cores = mc.cores, .env = .env))
> 
> [[8]] .consensus_partition(data = data, top_value_method = top_value_method, top_n = top_n, partition_method = partition_method, k = 2:max_k, p_sampling = p_sampling, sample_by = sample_by, partition_repeat = partition_repeat, partition_param = partition_param, anno = anno, anno_col = anno_col, scale_rows = scale_rows, verbose = verbose, mc.cores = mc.cores, .env = .env)
> 
> [[9]] rbind(param, lt[[i]]$param)
> 
> [[10]] rbind(deparse.level, ...)
> 
> [[11]] .handleSimpleError(function (e) { cat(message, "\n") cat("Following is the call stack:\n") print(sys.calls()) }, "$ operator is invalid for atomic vectors", base::quote(NULL))
> 
> [[12]] h(simpleError(msg, call))
> 
> Error: $ operator is invalid for atomic vectors In addition: Warning message: In mclapply(seq_len(partition_repeat), function(j) { : all scheduled cores encountered errors in user code Timing stopped at: 3.332 3.451 4.742

Okay. I installed the package now from github and I don't see the above error. But in the report I see the follwoing error.

![image](https://user-images.githubusercontent.com/11817153/142293089-1df01b70-1d22-4733-98b8-e8bc23d20418.png)

**Comment by venkan** [comment]
Okay. I installed the package now from github and I don't see the above error. But in the report I see the follwoing error.

![image](https://user-images.githubusercontent.com/11817153/142293089-1df01b70-1d22-4733-98b8-e8bc23d20418.png)

**Comment by jokergoo** [comment]
What is the value returned by `get_anno_col(res_list)`? The value should be a list of named vectors.
