### ISSUE TITLE
Error: $ operator is invalid for atomic vectors in search_tweets 

### ISSUE THREAD

**Issue by Sue596** [jokergoo/cola#173]
library(tidyverse) 
library(rtweet) 
rtweet:::default_cached_auth() 
auth_setup_default()  # the screen will show
# Authentication complete. Please close this page and return to R.

tweets <- search_tweets(q="#Actually",n=1000, include_rts = FALSE,
                         retryonratelimit = TRUE)  

Hi, I always got error as "Error: $ operator is invalid for atomic vectors", i donot know why ? I am really apprecited.

**Comment by jokergoo** [comment]
This issue has nothing related to the cola package.
