### ISSUE TITLE
Determination of default top_n

### ISSUE THREAD

**Issue by KevDonn** [jokergoo/cola#176]
Hi,

Thanks for creating this package, it's enormously helpful. I have a query as to how 'top_n' is determined when it is not specified in the consensus_partition() function. 

According to the help file, 'top_n' defaults to 'NULL'. Running my own analysis, my initial matrix has 26,965 rows. Using MAD, the top  1451 rows are selected; using ATC, the top 2696 are selected. So I was wondering, what are the criteria for selecting the top rows?

Many thanks,
Kevin

**Comment by jokergoo** [comment]
I think the documentation has not been updated. You can see the method here:

https://academic.oup.com/bib/article/23/3/bbac048/6548376#355035230

> In the iterative execution of CP on every submatrix, top features are firstly selected. Generally, secondary subgroups have less efficient features for classification, thus setting the same number of top features for all submatrices would bring additional noise and destabilize the classification for secondary subgroups. Therefore, a method is needed for automatic selection of proper numbers of top features on each node in HCP. This corresponds to the task of selecting a cutoff for filtering top-values. A reasonable way is to select the ‘elbow’ of the top-value curve if top-values are sorted increasingly. Here we use the method proposed in Satopaa et al. [[13](javascript:;)]. It selects the point that has the largest vertical offset to the straight line that connects the points with the minimal and the maximal top-values. More details can be found in [Supplementary File 2](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bib/23/3/10.1093_bib_bbac048/1/suppl_02_bbac048.pdf?Expires=1668254925&Signature=k6AKvPH4ntqqE2mSat7RiYN866IsC48Iza3-OqHeo1I53Kdsn7zvvCCgGRihAVcPNELZJhDUR6Me~J9JSMSBndoSfMN3QuuEpelyc-QXusUXN9cELccc0GE7wOmtSvq~5lcIeo1f2CgOGwOkjeMF22JbLFFrH5iHONfIbC~Ql7dA4jw2ihvaFZ1g3TZrx3QEYmvU2KH7~x2mxg3fSe2gmf4c0xXKW5Eu~utNEsTqSL6YB9qFTrFGqoxOG9XxDNEpcPusfb8xqg~rv8v5lrdGCBQSmSsyPjatfEEuAdHcXO~saUBhSBRbD6xrGFGCqACdnPM7ETvi3WMlJbJ3K1QdCg__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA).

**Comment by KevDonn** [comment]
Ah, I wasn't aware of this manuscript! I had suspected that there was an underlying rationale. Ideal, thanks again.
