### ISSUE TITLE
How can I get the gene signatures from every cluster?

### ISSUE THREAD

**Issue by Phoenix12580** [jokergoo/cola#180]

**Comment by jokergoo** [comment]
If you run `get_signatures()`:

```r
df = get_signatures(...)
```

the clusters of genes are in the object `df`.

**Comment by Phoenix12580** [comment]
Thank you very much！

> If you run `get_signatures()`:
> 
> ```r
> df = get_signatures(...)
> ```
> 
> the clusters of genes are in the object `df`.

Thank you very much！
