### ISSUE TITLE
How to change the colors of consensus_heatmap

### ISSUE THREAD

**Issue by Phoenix12580** [jokergoo/cola#181]

**Comment by jokergoo** [comment]
The blue color is hard coded, but you can change it by the following trick:

```r
ht_list = consensus_heatmap(...)
ht_list@ht_list$Consensus@matrix_color_mapping@col_fun = colorRamp2(c(0, 1), c("white", "red"))
```

**Comment by Phoenix12580** [comment]
> The blue color is hard coded, but you can change it by the following trick:
> 
> ```r
> ht_list = consensus_heatmap(...)
> ht_list@ht_list$Consensus@matrix_color_mapping@col_fun = colorRamp2(c(0, 1), c("white", "red"))
> ```

Thank you very much , I will try it.
