### ISSUE TITLE
Reproducibility in parallel?

### ISSUE THREAD

**Issue by jarbet** [jokergoo/cola#182]
I notice when using `cores = 1` the clustering is reproducible.  However, when `cores > 1`, the results are not reproducible.

Would it be possible to make it so results are reproducible when `cores > 1`?

Example:

```
library(cola);
run.cola <- function(cores) {
    set.seed(123);
    
    # simulate example data
    m <- cbind(
        rbind(
            matrix(rnorm(20*20, mean = 1), nr = 20),
            matrix(rnorm(20*20, mean = -1), nr = 20)
            ),
        rbind(
            matrix(rnorm(20*20, mean = -1), nr = 20),
            matrix(rnorm(20*20, mean = 1), nr = 20)
            )
        );
    m <- m + matrix(rnorm(40 * 40), nr = 40);
    
    # run clustering
    rl <- run_all_consensus_partition_methods(
        data = m,
        top_n = c(10, 20),
        partition_method = c('hclust', 'kmeans'),
        max_k = 4,
        cores = cores
        );

return(rl)
}


### cores = 1: reproducible
a <- run.cola(cores = 1);
b <- run.cola(cores = 1);

identical(get_stats(a, k = 4), get_stats(b, k = 4));
[1] TRUE
identical(get_classes(a, k = 4)$class, get_classes(b, k = 4)$class);
[1] TRUE

### cores > 1: not reproducible
d <- run.cola(cores = 4);
e <- run.cola(cores = 4);

identical(get_stats(d, k = 4), get_stats(e, k = 4));
[1] FALSE
identical(get_classes(d, k = 4)$class, get_classes(e, k = 4)$class);
[1] FALSE

```

**Comment by jokergoo** [comment]
You are right. When multiple cores are turned one, you cannot set a random seed for that.

Let me find a solution...

**Comment by jokergoo** [comment]
Now I use **doRNG** package for parallel computing. In theory if you set the same seed by `set.seed()`, the classifications will be the same.

PS. the objects might not be the same because the objects also contain functions and environments, but for the non-environment parts in the object, I just had a quick check and they are the same if the objects are generated from the same seed.

**Comment by jarbet** [comment]
> Now I use **doRNG** package for parallel computing. In theory if you set the same seed by `set.seed()`, the classifications will be the same.
> 
> PS. the objects might not be the same because the objects also contain functions and environments, but for the non-environment parts in the object, I just had a quick check and they are the same if the objects are generated from the same seed.

I installed the latest version from github `2.5.1` and now setting a seed before `run_all_consensus_partition_methods()` leads to reproducible clusters when parallel computing.  Thanks!
