### ISSUE TITLE
apply cola to multiple-omic datasets ?

### ISSUE THREAD

**Issue by ChengYunazhi** [jokergoo/cola#80]
Hi Zuguang,

  Can cola be applied to the analysis of multiple omics data ？another bioconductor package named "CancerSubtypes" provide methods such as "iCluster", "Similarity network fusion", and "Ensemble method of SNF and CC" to handle multiple omic data. 

Is it possible to register above mentioned method in cola like code which register NMF in manual of cola to process multiple omic data?

All the best!

Yuanzhi

**Comment by jokergoo** [comment]
I don't know. I have no knowledge of multi-omics analysis. **cola** just does consensus clustering and I don't how it can be applied to multiple omics data. Maybe apply the clustering on different data types and finally compares the similarity of the partitions.

But thanks for letting me know this tool. I will definitely have a look!
