### ISSUE TITLE
Could cola export plot format such as pdf for specific plot

### ISSUE THREAD

**Issue by Byronxy** [jokergoo/cola#90]
Hi, Zuguang. When I use the function such as `collect_plots` with specific parameters. However, I could not find the path where the plot is. And also I hope to output pdf format plot, is there any method to deal with it? Thanks a lot!

**Comment by jokergoo** [comment]
Can you do:

```r
pdf(...)
collect_plots(...)
dev.off()
```

**Comment by Byronxy** [comment]
It works. Thanks a lot!
